In [24]:
from PIL import Image,ImageOps
import numpy as np
import pdfplumber
#E:/rag-project/data/raw/standards/附件1-1  上海海洋大学信息学院本科教学工作委员会工作职责.pdf

pdf = pdfplumber.open(r"E:/rag-project/data/raw/standards/附件1-5  上海海洋大学信息学院课程体系合理性评价办法.pdf")
page = [page for page in pdf.pages]
print(page)
img = page[1].to_image(resolution=300).original.convert("RGB")

arr = np.array(img)
print(arr)
r, g, b = arr[:,:,0], arr[:,:,1], arr[:,:,2]

# 红色判定条件（可调）
mask = (r > 210)
mask_black = (r < 210) & (g < 210) & (b <210)
# 方式1：变白
arr[mask] = [255, 255, 255]
arr[mask_black] = [0,0,0]
out = Image.fromarray(arr)
out.save("page1.png")


[<Page:1>, <Page:2>, <Page:3>]
[[[208 209 204]
  [239 240 235]
  [248 247 242]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[247 247 245]
  [250 251 246]
  [251 250 246]
  ...
  [254 254 254]
  [254 254 254]
  [255 255 255]]

 [[255 255 255]
  [253 253 251]
  [253 253 251]
  ...
  [254 254 254]
  [254 254 254]
  [255 255 255]]

 ...

 [[255 255 255]
  [254 254 255]
  [254 254 254]
  ...
  [ 68  74  86]
  [ 41  48  66]
  [  0   5  24]]

 [[255 255 255]
  [254 254 255]
  [254 254 254]
  ...
  [  1   8  18]
  [  0   5  21]
  [  0   6  24]]

 [[242 242 244]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   4]
  [  0   0   5]
  [  0   0   5]]]


In [26]:
import pytesseract
gray = ImageOps.grayscale(out)
gray.save("gray.jpg")
test = pytesseract.image_to_string(gray,lang="chi_sim")
print(test)

信息学院教学咨询委员会章程

(2020 年修订)
第一章 总 则

第一条 为了进一步创新办学模式、深化教学改革、加强校企
合作、推进产学研一体化和专业国际工程认证工作,， 上海海洋大学信
息学院〈 简称“信息学院” ) 特制订本委员会章程。

第二条 ”委员会的名称: 上海海洋大学信息学院教学咨询委员
会，简称“教学咨询委员会”。

第三条 委员会的性质: 本委员会是上海海洋大学信息学院与
知名企业联系的桥梁与纽带; 致力于推进学院与企业在人才培养、专
业建设、课程建设、实习就业、实训基地建设等方面的合作; 是创新
办学模式、探索校企合作、推进专业国际工程认证的平台和有力保障。

第四条 ”委员会的原则: 优势互补、资源共享、互惠互利、共
同发展， 促进学院与企业进行深层次校企合作,共同培养应用型创新
人才。

第五条 ”本委员会的活动方式: 通过定期会议、参观考察、高
层会商的方式，加强委员单位问的联系，增进相互了解。

第六条 ”本委员会办公地点: 上海海洋大学信息学院。

第七条 ”信息学院职责

(一) 负责制订教学咨询委员会和学院校企合作年度工作计划、
下发通知、撰写总结等日常工作;

(二 ) 负责组织开展学校与企业在人才培养、科技合作、实训基
地建设、产学一体化等方面的合作事项;



In [ ]:
import pymupdf4llm
import pathlib
md_text = pymupdf4llm.to_markdown(r"E:/rag-project/data/raw/standards/附件1-14 上海海洋大学信息学院本科专业毕业要求达成情况评价办法.pdf")
print(md_text)
pathlib.Path("output.md").write_bytes(md_text.encode())

Consider using the pymupdf_layout package for a greatly improved page layout analysis.
酽



|∷ ∶


# 上海海洋大学信息学院本科专业毕业要求达成情况 评价办 [法]

毕业要求达成情况评价是检验和判断专业人才培养质量是否达到毕业要求


的重要保障机制,也 是专业持续改进教学 [工] 作的重要依据 [。] 为发现学生能力短板 [,]

改进培养方案,确 保专业人才培养质量,以 [“] 学生为中心 [、] 产出导向 [、] 持续改进 [”]


为指导,特 制订本办法 [。]


一、评价目的


毕业要求是对学生毕业时应该掌握的知识和能力的具体描述,是 学生完成学


业时应该取得的学习成果,毕 业要求达成是培养目标与课程目标之间的重要环节。


通过毕业要求达成系统化、形成性和合理性评价,将 毕业要求落实到每门课程和


每位教师中,为 专业教育提供持续改进的依据,最 终保证专业毕业要求的达成 [,]


人才培养质量得到提升。


二、评价对象及周期


1.评 价对象:本 科各专业每 [一] 届所有取得毕业证书的毕业生,针 对12条毕


业要求,逐 项进行评价,考 查其毕业要求达成。


2.评价周期:在 学生学满四年毕业时,完成各项毕业要求指标的达成度评价 [,]


根据各项毕业要求达成情况评价值 [,判] 定本届学 [生] 对于毕 [业] 要求的 [达成] 情况 [。为]


保证专业的工程教育质量,专业要求每门课程的达成情况评价周期为 [1年] ;每年

###### 对每届毕业生进行毕业要求达成情况评价;对 毕业要求合理性评价周期为 [2年] [。]


三、评价机构


上海海洋大学信息学院本科专业毕业要求达成情况评价主要由学院教学 [工]
##### 作委员会、专业达成评价 [工] 作组及具体 [工] 作人员参与协调与实施 [,从] 教 [学环] 节 [、]


毕业生、毕业设计 [(论] 文)导 师 [三] 方面进行毕业要求达成情况评价 [(表] [1)。]


表 1评 价活动与评价组 [织] [(人] 员 [)]


评价 [活] 动 参与 [人] 员或机构

统筹协调评价工作 学院分管教学副 [院] 长

制定评价标准与评价方 [法],审 

13191

In [ ]:
import pymupdf4llm

# 启用 OCR
md_text = pymupdf4llm.to_markdown(
    r"E:/rag-project/data/raw/standards/附件1-1  上海海洋大学信息学院本科教学工作委员会工作职责.pdf",
    ocr=True,                # 👈 核心参数
    ocr_language="chi_sim"   # 中文简体
)

print(md_text)


Warning - arguments ignored in legacy mode: {'ocr', 'ocr_language'}.



In [ ]:
from langchain_community.document_loaders import UnstructuredPDFLoader
loader = UnstructuredPDFLoader(r"E:/rag-project/data/raw/programs/大数据-2025级本科生培养方案-v13-724.pdf")
data = loader.load()
print(data)

[Document(metadata={'source': 'E:\\rag-project\\data\\raw\\programs\\大数据-2025级本科生培养方案-v13-724.pdf'}, page_content='专业负责人：卢鹏、张晨静\n\n数据科学与大数据技术专业 （Data Science and Big Data Technology）\n\n学科门类：工学 专业类：计算机类 专业代码：080910T\n\n一、培养目标与毕业要求\n\n1. 培养目标\n\n以习近平新时代中国特色社会主义思想为指导，落实立德树人根本任务，坚持为党育人，\n\n为国育才，本专业旨在培养适应中国特色社会主义现代化建设和未来社会与科技发展需求，具\n\n备人文、社会科学素养，爱国敬业，遵纪守法，拥有创新精神与国际化视野，具备解决专业领\n\n域复杂工程问题的能力，能够在智慧海洋、生物信息等相关领域，从事软件开发、计算机系统\n\n维护、大数据分析处理、项目管理等工作的复合应用型新时代专业人才，培养德智体美劳全面\n\n发展的社会主义建设者和接班人。\n\n预期在毕业 5 年左右，能达到以下目标：\n\n目标 1：具有工程职业素养、社会责任感和民族自信心，能够将工程实践与社会发展良性\n\n结合。\n\n目标 2：有较强的团队合作能力和组织管理能力，能够胜任项目或团队管理工作，担任项\n\n目或团队负责人。\n\n目标 3：具有国际视野和竞争意识，能够把握大数据行业及其技术发展趋势，适应信息产\n\n业和社会经济的新发展，在跨文化、多学科背景下开展交流与竞争。\n\n目标 4：具有终身学习能力，能够不断丰富和加深专业知识的学习和理解，适应岗位工作\n\n和事业发展要求。\n\n目标 5：具有创新和优化复杂工程解决方案的能力，能够在智慧海洋、生物信息等相关行\n\n业发挥优势。\n\n2. 毕业要求\n\n（1）工程知识：了解专业领域相关工程基础理论，能够将数学、自然科学、计算、工程基\n\n础和专业知识用于解决复杂数据工程问题。\n\n（2）问题分析：能够应用数学、自然科学和工程科学的基本原理，识别、表达、并通过文\n\n献研究分析复杂数据工程问题，综合考虑可持续发展的要求，以获得有效结论。\n\n（3）设计/开发解决方案：能够设计针对复杂数据工程问题的解决方案，

In [3]:
import langchain
langchain.__version__

'1.2.0'

In [9]:
"""
Utility function for showing images.

Intended to be imported in Jupyter notebooks to display pixmap images.

Invocation: "show_image(item, title)", where item is a PyMuPDF object
which has a "get_pixmap" method, and title is an optional string.

The function executes "item.get_pixmap(dpi=150)" and show the resulting
image.


Dependencies
------------
numpy, matplotlib, pymupdf
"""


def show_image(item, title=""):
    """Display a pixmap.

    Just to display Pixmap image of "item" - ignore the man behind the curtain.

    Args:
        item: any PyMuPDF object having a "get_pixmap" method.
        title: a string to be used as image title

    Generates an RGB Pixmap from item using a constant DPI and using matplotlib
    to show it inline of the notebook.
    """
    DPI = 150  # use this resolution
    import numpy as np
    import matplotlib.pyplot as plt

    # %matplotlib inline
    pix = item.get_pixmap(dpi=DPI)
    img = np.ndarray([pix.h, pix.w, 3], dtype=np.uint8, buffer=pix.samples_mv)
    plt.figure(dpi=DPI)  # set the figure's DPI
    plt.title(title)  # set title of image
    _ = plt.imshow(img, extent=(0, pix.w * 72 / DPI, pix.h * 72 / DPI, 0))

In [29]:
import fitz
doc = fitz.open("E:/rag-project/data/raw/programs/大数据-2025级本科生培养方案-v13-724.pdf")
page = doc[3]
tabs = page.find_tables()  # detect the tables
for i,tab in enumerate(tabs):  # iterate over all tables
    print(i)
    print(tab.to_pandas)

0
<bound method Table.to_pandas of <pymupdf.table.Table object at 0x000001FD314297D0>>
1
<bound method Table.to_pandas of <pymupdf.table.Table object at 0x000001FD3013CF90>>
2
<bound method Table.to_pandas of <pymupdf.table.Table object at 0x000001FD313C5690>>
3
<bound method Table.to_pandas of <pymupdf.table.Table object at 0x000001FD318CD550>>


In [26]:
import fitz

pdf = fitz.open("E:/rag-project/data/raw/programs/大数据-2025级本科生培养方案-v13-724.pdf")
page = pdf[7]
pix = page.get_pixmap(dpi=300,colorspace=fitz.csRGB,alpha=False)

pix.save("page0.jpg")

In [28]:
from img2table.document import Image
from img2table.ocr import TesseractOCR

ocr = TesseractOCR(n_threads=1,lang="chi_sim")
img = Image(src="page0.jpg")
extracted_tables = img.extract_tables(ocr=ocr, implicit_rows=False, implicit_columns=False)
extracted_tables[0].df

,0,1,2
0,毕业 要 求,观测 点,课程 名 称
1,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )
2,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,统计
3,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...
4,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,离散 数学
5,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 二)
6,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,概率 论 与 数理 统计
7,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...
8,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,数据 科学 导论
9,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,高 等 数学 〈 一 、 二 )\n表 述 ) 掌握 专业 相关 数学 、 自 然 科\n学...,数据 挖掘


In [7]:
extracted_tables[0].title

'表 1 课程 体系 评价 的 方法 及 依据'

In [25]:
from img2table.document import PDF

pdf = PDF("E:/rag-project/data/raw/programs/大数据-2025级本科生培养方案-v13-724.pdf")

pdf_table = pdf.extract_tables(ocr=ocr,implicit_columns=True,implicit_rows=True,borderless_tables=True)
pdf.to_xlsx('table.xlsx',ocr=ocr)

e:\rag-project\.venv\Lib\site-packages\xlsxwriter\worksheet.py:2353: UserWarning: Can't merge single cell
  warn("Can't merge single cell")


In [10]:
pdf_table

{0: [],
 1: [ExtractedTable(title=毕业要求对培养目标的支撑关系矩阵（有支撑关系打√）, bbox=(221, 1265, 1433, 1848),shape=(12, 6))],
 2: [ExtractedTable(title=六、毕业学分基本要求, bbox=(221, 1774, 1429, 1919),shape=(3, 9))],
 3: [ExtractedTable(title=（1）通识教育课程, bbox=(221, 272, 1433, 581),shape=(5, 6)),
  ExtractedTable(title=（2）公共基础课程, bbox=(221, 655, 1432, 833),shape=(3, 9)),
  ExtractedTable(title=公共基础课, bbox=(221, 908, 1433, 1248),shape=(7, 11)),
  ExtractedTable(title=学科基础课, bbox=(221, 1511, 1433, 2079),shape=(11, 11))],
 4: [ExtractedTable(title=None, bbox=(221, 221, 1433, 513),shape=(6, 11)),
  ExtractedTable(title=专业必修课, bbox=(221, 611, 1433, 1000),shape=(8, 11)),
  ExtractedTable(title=专业选修课（最低应修 15 学分）, bbox=(221, 1074, 1433, 2080),shape=(16, 11))],
 5: [ExtractedTable(title=None, bbox=(221, 221, 1232, 351),shape=(2, 8)),
  ExtractedTable(title=专业实践实训, bbox=(221, 425, 1433, 1475),shape=(19, 11)),
  ExtractedTable(title=None, bbox=(221, 1595, 1432, 2033),shape=(9, 14))],
 6: [ExtractedTable(title=None, bbox=(221

In [7]:
import tabula
dfs = tabula.read_pdf("E:/rag-project/data/raw/programs/大数据-2025级本科生培养方案-v13-724.pdf",page=all)

AttributeError: module 'tabula' has no attribute 'read_pdf'

In [1]:
from marker.converters.pdf import PdfConverter
from marker.models import create_model_dict
from marker.output import text_from_rendered

converter = PdfConverter(
    artifact_dict=create_model_dict()
)
rendered = converter("大数据-2025级本科生培养方案-v13-724.pdf")
text, _, images = text_from_rendered(rendered=rendered)

Recognizing Text: 100%|██████████| 330/330 [00:05<00:00, 55.61it/s] 


In [2]:
text

'#### 专业负责人:卢鹏、张晨静\n\n# 数据科学与大数据技术专业 (**Data Science and Big Data Technology**)\n\n学科门类:工学专业类:计算机类专业代码:**080910T**\n\n#### 一、培养目标与毕业要求\n\n## **1.** 培养目标\n\n以习近平新时代中国特色社会主义思想为指导,落实立德树人根本任务,坚持为党育人, 为国育才,本专业旨在培养适应中国特色社会主义现代化建设和未来社会与科技发展需求,具 备人文、社会科学素养,爱国敬业,遵纪守法,拥有创新精神与国际化视野,具备解决专业领 域复杂工程问题的能力,能够在智慧海洋、生物信息等相关领域,从事软件开发、计算机系统 维护、大数据分析处理、项目管理等工作的复合应用型新时代专业人才,培养德智体美劳全面 发展的社会主义建设者和接班人。\n\n预期在毕业 5 年左右,能达到以下目标:\n\n- 目标 **1**:具有工程职业素养、社会责任感和民族自信心,能够将工程实践与社会发展良性 结合。\n- 目标 **2**:有较强的团队合作能力和组织管理能力,能够胜任项目或团队管理工作,担任项 目或团队负责人。\n- 目标 **3**:具有国际视野和竞争意识,能够把握大数据行业及其技术发展趋势,适应信息产 业和社会经济的新发展,在跨文化、多学科背景下开展交流与竞争。\n- 目标 **4**:具有终身学习能力,能够不断丰富和加深专业知识的学习和理解,适应岗位工作 和事业发展要求。\n- 目标 **5**:具有创新和优化复杂工程解决方案的能力,能够在智慧海洋、生物信息等相关行 业发挥优势。\n\n#### **2.** 毕业要求\n\n- (**1**)工程知识:了解专业领域相关工程基础理论,能够将数学、自然科学、计算、工程基 础和专业知识用于解决复杂数据工程问题。\n- (**2**)问题分析:能够应用数学、自然科学和工程科学的基本原理,识别、表达、并通过文 献研究分析复杂数据工程问题,综合考虑可持续发展的要求,以获得有效结论。\n- (**3**)设计**/**开发解决方案:能够设计针对复杂数据工程问题的解决方案,设计满足特定需求 的大数据系统、软硬件或相关产品,并能够在设计环节中体现创新性,考虑健康、安全与环境、\n\n全生命周期成本与净零碳要求、法律与伦理、社

In [3]:
from pathlib import Path
test_path = Path(".")/"marker-test.md"
test_path.write_text(text, encoding="utf-8")
print("已生成")

已生成


In [ ]:
from marker.converters.table import TableConverter
from marker.models import create_model_dict
from marker.output import text_from_rendered

converter = TableConverter(
    artifact_dict=create_model_dict(),
)
rendered = converter("大数据-2025级本科生培养方案-v13-724.pdf")
text, _, images = text_from_rendered(rendered)

Recognizing Text: 100%|██████████| 330/330 [00:05<00:00, 56.54it/s] 


In [5]:
text

'|            | 目标<br>1 | 目标<br>2 | 目标<br>3 | 目标<br>4 | 目标<br>5 |\n|------------|---------|---------|---------|---------|---------|\n| 毕业要求<br>1  |         |         |         |         | √       |\n| 毕业要求<br>2  |         |         |         |         | √       |\n| 毕业要求<br>3  |         |         |         |         | √       |\n| 毕业要求<br>4  |         |         | √       | √       |         |\n| 毕业要求<br>5  |         |         |         |         | √       |\n| 毕业要求<br>6  | √       | √       |         | √       |         |\n| 毕业要求<br>7  | √       |         |         |         |         |\n| 毕业要求<br>8  |         | √       |         |         |         |\n| 毕业要求<br>9  |         | √       | √       |         |         |\n| 毕业要求<br>10 |         | √       |         |         | √       |\n| 毕业要求<br>11 |         |         | √       | √       |         |\n\n|        | 准予  |    | 通识教育课程 | 公共基础课程 |       |    | 专业教育课程 |        |\n|--------|-----|----|--------|--------|-------|----|--------|------

In [6]:
from pathlib import Path
test_path = Path(".")/"marker-table-test.md"
test_path.write_text(text, encoding="utf-8")
print("已生成")

已生成


In [6]:
from marker.converters.pdf import PdfConverter
from marker.models import create_model_dict
from marker.output import text_from_rendered

converter = PdfConverter(
    artifact_dict=create_model_dict()
)
rendered = converter("附件1-5  上海海洋大学信息学院课程体系合理性评价办法.pdf")
text, _, images = text_from_rendered(rendered=rendered)

Recognizing Text: 100%|██████████| 57/57 [00:01<00:00, 34.66it/s]


In [16]:
print(text)

# 上海海洋大学信息学院文件

沪海大信息 [2021] 行 6 号

# 上海海洋大学信息学院课程体系合理性评价办法

课程是实现毕业要求的基本单元,课程设置必须能够有效支持毕业要求的达成。为建立课程体系合理性评价机制,确保整个课程体系能够覆盖全部毕业要求,每门课程能够实现其在课程体系中的作用,支撑各专业人才培养目标的达成,特制订本办法。

## 一、评价机构

信息学院教学工作委员会

### 二、评价方法及依据

信息学院教学工作委员会根据《普通高等学校本科专业类教学质量国家标准》、《工程教育认证通用标准》及《计算机类专业补充标准》,采用校内与校外评价主体相结合的方法对课程体系设置进行合理性评价。校内主要通过课程目标达成情况评价及改进报告、毕业要求达成情况评价报告、专业教师问卷调查、在校生问卷调查等多种方式进行评价。校外主体主要通过企业行业专家、用人单位、毕业生调研反馈意见等进行评价。具体评价方法及依据如表 1 所示。

| 衣   体性体系计例的方法及依据 |   |      |                       |              |  |  |
|------------------|---|------|-----------------------|--------------|--|--|
| 评价指标             |   |      | 评价内容                  | 评价依据         |  |  |
| 对                | 毕 | 单个指标 | 1. 课程体系与毕业要求指标点关联关系是否 | 1. 毕业要求达成情况  |  |  |
| 业                | 要 | 点的支撑 | 能够实现覆盖支撑关系,课程矩阵是否合理;  | 评价报告;        |  |  |
| 求                | 指 | 情况   | 2. 各门课程的权重是否合理;       | 2. 课程目标达成情况  |  |  |
| 标                | 点 | 单门课程 | 1. 课程目标与指标点的对应是否合理;   | 报告 (年度报告);   |  |  |
| 的                | 支 | 支撑指标 | 2. 课程主要内容

In [7]:
from pathlib import Path
test_path = Path(".")/"附件1-5  上海海洋大学信息学院课程体系合理性评价办法.md"
test_path.write_text(text, encoding="utf-8")
print("已生成")

已生成


In [5]:
import fitz  # PyMuPDF
from pathlib import Path
from marker.converters.pdf import PdfConverter
from marker.models import create_model_dict
from marker.output import text_from_rendered

def test_marker_official_by_page(input_pdf: str, output_md: str):
    """
    使用官方最新 API 逐页处理 PDF，并注入页码标记。
    """
    input_path = Path(input_pdf)
    if not input_path.exists():
        print(f"❌ 找不到文件: {input_pdf}")
        return

    # 1. 初始化转换器（只需加载一次，对应你提供的官方写法）
    print("⏳ 正在初始化 Marker 模型字典（此过程较慢，请稍候）...")
    converter = PdfConverter(
        artifact_dict=create_model_dict(),
    )
    
    # 2. 打开原始 PDF 并创建临时目录
    doc = fitz.open(input_pdf)
    total_pages = len(doc)
    temp_dir = Path("./temp_split_pages")
    temp_dir.mkdir(exist_ok=True)
    
    all_page_contents = []

    try:
        for i in range(total_pages):
            current_page_num = i + 1
            print(f"🔄 [进度 {current_page_num}/{total_pages}] 正在处理中...")

            # 3. 提取单页并保存为临时文件
            temp_pdf_path = temp_dir / f"page_{current_page_num}.pdf"
            single_page_doc = fitz.open()
            single_page_doc.insert_pdf(doc, from_page=i, to_page=i)
            single_page_doc.save(str(temp_pdf_path))
            single_page_doc.close()

            # 4. 调用官方最新接口进行转换
            # 使用你提供的官方 API 流程
            rendered = converter(str(temp_pdf_path))
            text, _, _ = text_from_rendered(rendered)

            # 5. 注入自定义页码标记 (HTML 注释格式)
            # 这种格式在 Markdown 渲染中是隐藏的，但对我们的分块脚本（Chunking）可见
            marked_text = f"\n\n\n{text}\n\n"
            all_page_contents.append(marked_text)

            # 清理单页临时文件
            temp_pdf_path.unlink()

        # 6. 合并所有页面内容并保存
        final_md_path = Path(output_md)
        with open(final_md_path, "w", encoding="utf-8") as f:
            f.write("\n---\n".join(all_page_contents))
        
        print(f"\n✨ 处理完成！最终文件：{final_md_path.absolute()}")

    finally:
        # 彻底清理临时目录
        if temp_dir.exists():
            for f in temp_dir.glob("*"): f.unlink()
            temp_dir.rmdir()
        doc.close()

if __name__ == "__main__":
    # --- 测试配置 ---
    # 建议先找一个页数较少的 PDF（如 2-3 页）进行测试
    test_pdf = "附件1-5  上海海洋大学信息学院课程体系合理性评价办法.pdf" 
    output_result = "marker_test_official.md"
    
    test_marker_official_by_page(test_pdf, output_result)

⏳ 正在初始化 Marker 模型字典（此过程较慢，请稍候）...
🔄 [进度 1/3] 正在处理中...


Recognizing Text: 100%|██████████| 34/34 [00:41<00:00,  1.22s/it]


🔄 [进度 2/3] 正在处理中...


Recognizing Text: 100%|██████████| 24/24 [00:00<00:00, 24.55it/s]


🔄 [进度 3/3] 正在处理中...


Recognizing Text: 100%|██████████| 6/6 [00:00<00:00,  8.47it/s]
Detecting bboxes: 0it [00:00, ?it/s]


✨ 处理完成！最终文件：e:\rag-project\experiments\test\marker_test_official.md


In [10]:
"""基于 LangChain 的增强型分块模块。

支持从带有 ==== PAGE_X_START ==== 标记的 Markdown 中提取物理页码元数据。
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Sequence

from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter

__all__ = ["chunk_markdown_file", "chunk_all_documents"]

Chunk = Dict[str, object]

def _build_chunk(
    source_file: Path,
    text: str,
    seq: int,
    metadata: Dict[str, object] | None = None,
) -> Chunk:
    """构造增强型 chunk 字典结构。"""
    meta = {
        "source": source_file.name,
        "chunk_seq": seq,
        "file_path": str(source_file),
        **(metadata or {})
    }
    chunk_id = f"{source_file.stem}#{seq}"
    return {
        "chunk_id": chunk_id,
        "text": text,
        "metadata": meta,
    }

def _md_header_splitter() -> MarkdownHeaderTextSplitter:
    """按工程认证文档常用的三级标题进行初步语义拆分。"""
    headers = [("#", "h1"), ("##", "h2"), ("###", "h3")]
    return MarkdownHeaderTextSplitter(headers_to_split_on=headers)

def _recursive_splitter(chunk_size: int = 800, chunk_overlap: int = 150) -> RecursiveCharacterTextSplitter:
    """递归字符分割器，优先保证中文句子的完整性。"""
    return RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", "。", "！", "？", "；", " ", ""],
    )

def _clean_table_whitespace(text: str) -> str:
    """
    专门针对 Markdown 表格单元格内的多余空格进行脱水。
    """
    lines = []
    for line in text.splitlines():
        # 仅对包含表格分隔符的行进行处理
        if '|' in line:
            # 1. 按照 | 分割
            parts = line.split('|')
            # 2. 对每个部分进行处理：
            #    - strip() 去除首尾空格
            #    - re.sub(r'\s+', ' ', ...) 将内部连续多个空格压缩为一个
            cleaned_parts = [re.sub(r'\s+', ' ', p.strip()) for p in parts]
            # 3. 重新组装，保留 Markdown 表格结构
            new_line = "|".join(cleaned_parts)
            lines.append(new_line)
        else:
            lines.append(line)
    return "\n".join(lines)

def _clean_text_density(text: str) -> str:
    """
    对 Markdown 文本进行“脱水”处理，提高信息密度。
    """
    # 1. 去除每行行首和行尾的空白字符
    text = _clean_table_whitespace(text)
    text = "\n".join([line.strip() for line in text.splitlines()])
    
    # 2. 压缩连续的换行符 (3个及以上压缩为2个，保留 Markdown 的段落感)
    text = re.sub(r'\n{3,}', '\n\n', text)
    
    # 3. 清理截图中的 <br> 标签 (可选，建议替换为空格或直接删除)
    text = text.replace("<br>", " ")
    
    # 4. 特殊处理：针对表格中间的大量空行
    # 如果一行只有 | 和空格，通常是空表格行，可以根据需求决定是否删除
    # text = re.sub(r'^\|[\s\|]+\|$', '', text, flags=re.MULTILINE)
    
    return text.strip()

def chunk_markdown_file(path: Path, chunk_size: int = 1300, chunk_overlap: int = 400) -> List[Chunk]:
    """
    处理带页码锚点的 Markdown 文件：
    1. 按标题层级做初步切分。
    2. 按字符长度做二次切分。
    3. 实时捕获并清理页码锚点，将页码存入 metadata。
    """
    raw_text = path.read_text(encoding="utf-8")
    
    text = _clean_text_density(raw_text)
    header_splitter = _md_header_splitter()
    length_splitter = _recursive_splitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)

    # 1. 语义分块（保留标题层级信息）
    docs = header_splitter.split_text(text)
    
    chunks: List[Chunk] = []
    seq = 1
    last_seen_page = 1  # 默认起始页

    for doc in docs:
        # 提取标题元数据
        headers = [str(v) for v in doc.metadata.values()]
        
        # 2. 长度分块
        sub_docs = length_splitter.split_documents([doc])
        
        for sub in sub_docs:
            content = sub.page_content
            
            # 3. 页码追踪：在分块中寻找注入的英文锚点
            # 匹配模式：==== PAGE_5_START ====
            page_matches = re.findall(r'==== PAGE_(\d+)_START ====', content)
            
            if page_matches:
                # 记录块内出现的所有页码（处理跨页情况）
                page_labels = sorted(list(set(int(p) for p in page_matches)))
                last_seen_page = page_labels[-1]  # 更新最后看到的页码
            else:
                # 若块内无锚点，则属于上个锚点的后续范围
                page_labels = [last_seen_page]

            # 4. 正文清理：剔除用于定位的锚点，保持知识库内容纯净
            # 防止大模型生成时带出 "==== PAGE_X_START ====" 噪声
            clean_text = re.sub(r'==== PAGE_\d+_(START|END) ====', '', content).strip()
            
            # 5. 组装 Chunk
            chunks.append(
                _build_chunk(
                    source_file=path,
                    text=clean_text,
                    seq=seq,
                    metadata={
                        "headers": headers,
                        "page_labels": page_labels,
                        "is_cross_page": len(page_labels) > 1
                    },
                )
            )
            seq += 1
            
    return chunks

def chunk_all_documents(
    md_root: Path | None = None,
    chunk_size: int = 1000,
    chunk_overlap: int = 250,
) -> List[Chunk]:
    """统一处理 data/parsed/md 下的所有已转换文件。"""
    

    all_chunks: List[Chunk] = []

    # 扫描目录下所有 .md 文件
    md_file = Path("大数据-2025级本科生培养方案-v13-724.md")
    print(md_file)
    all_chunks.extend(chunk_markdown_file(md_file, chunk_size=chunk_size, chunk_overlap=chunk_overlap))

    return all_chunks

if __name__ == "__main__":
    # 快速测试
    chunks = chunk_all_documents()
    print(chunks)
    print(f"✅ 处理完成，总分块数: {len(chunks)}")

大数据-2025级本科生培养方案-v13-724.md
[{'chunk_id': '大数据-2025级本科生培养方案-v13-724#1', 'text': '#### 专业负责人:卢鹏、张晨静', 'metadata': {'source': '大数据-2025级本科生培养方案-v13-724.md', 'chunk_seq': 1, 'file_path': '大数据-2025级本科生培养方案-v13-724.md', 'headers': [], 'page_labels': [1], 'is_cross_page': False}}, {'chunk_id': '大数据-2025级本科生培养方案-v13-724#2', 'text': '学科门类:工学专业类:计算机类专业代码:**080910T**', 'metadata': {'source': '大数据-2025级本科生培养方案-v13-724.md', 'chunk_seq': 2, 'file_path': '大数据-2025级本科生培养方案-v13-724.md', 'headers': ['数据科学与大数据技术专业 (**Data Science and Big Data Technology**)'], 'page_labels': [1], 'is_cross_page': False}}, {'chunk_id': '大数据-2025级本科生培养方案-v13-724#3', 'text': '以习近平新时代中国特色社会主义思想为指导,落实立德树人根本任务,坚持为党育人, 为国育才,本专业旨在培养适应中国特色社会主义现代化建设和未来社会与科技发展需求,具 备人文、社会科学素养,爱国敬业,遵纪守法,拥有创新精神与国际化视野,具备解决专业领 域复杂工程问题的能力,能够在智慧海洋、生物信息等相关领域,从事软件开发、计算机系统 维护、大数据分析处理、项目管理等工作的复合应用型新时代专业人才,培养德智体美劳全面 发展的社会主义建设者和接班人。  \n预期在毕业 5 年左右,能达到以下目标:  \n- 目标 **1**:具有工程职业素养、社会责任感和民族自信心,能够将工程实践与社会发展良性 结合。\n- 目标 **2**:有较强的团队合作能力和组织管理能力,能够胜任项目或团队管理工作,担任项 目或团队

In [ ]:
import json
import sys
from pathlib import Path
from typing import Iterable, List

def save_chunks_jsonl(chunks: Iterable[dict], output_path: Path) -> None:
    """将 chunk 列表写入 JSON Lines 文件，确认为 UTF-8 编码。"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        for chunk in chunks:
            # ensure_ascii=False 保证中文不被转义，方便调试查看
            f.write(json.dumps(chunk, ensure_ascii=False))
            f.write("\n")

In [11]:
import json
with Path("test_chunks.json").open("w",encoding="utf-8") as f:
    for chunk in chunks:
        f.write(json.dumps(chunk, ensure_ascii=False))
        f.write("\n")

In [1]:
# 创建一个名为 check_version.py 的文件并运行
import transformers
print(f"Transformers Version: {transformers.__version__}")
from transformers.utils import LossKwargs
print("Success!")

Transformers Version: 4.57.6


ImportError: cannot import name 'LossKwargs' from 'transformers.utils' (e:\rag-project\.venv\Lib\site-packages\transformers\utils\__init__.py)

In [2]:
import torch
print(torch.__version__)

2.10.0+cu126


In [1]:
from huggingface_hub import snapshot_download

# 下载到本地指定的目录
snapshot_download(
    repo_id="Kingsoft-LLM/QZhou-Embedding-Zh",
    local_dir="e:/rag-project/models/QZhou-Embedding-Zh",
    local_dir_use_symlinks=False
)

e:\rag-project\.venv\Lib\site-packages\huggingface_hub\file_download.py:979: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(


Fetching 26 files:   0%|          | 0/26 [00:00<?, ?it/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


1.png:   0%|          | 0.00/64.0k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/14.7M [00:00<?, ?B/s]

2.png:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


3.png:   0%|          | 0.00/37.3k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


5.png:   0%|          | 0.00/346k [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

4.png:   0%|          | 0.00/73.6k [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/336M [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model-00001-of-00004.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Error while downloading from https://huggingface.co/Kingsoft-LLM/QZhou-Embedding-Zh/resolve/a26c27aff5756ca78402258440ae20f09e9219bd/model-00003-of-00004.safetensors: HTTPSConnectionPool(host='cas-bridge.xethub.hf.co', port=443): Read timed out.
Trying to resume download...


model-00003-of-00004.safetensors:  19%|#9        | 954M/4.98G [00:00<?, ?B/s]

Error while downloading from https://huggingface.co/Kingsoft-LLM/QZhou-Embedding-Zh/resolve/a26c27aff5756ca78402258440ae20f09e9219bd/model-00002-of-00004.safetensors: HTTPSConnectionPool(host='cas-bridge.xethub.hf.co', port=443): Read timed out.
Trying to resume download...


model-00002-of-00004.safetensors:  36%|###6      | 1.79G/4.92G [00:00<?, ?B/s]

'E:\\rag-project\\models\\QZhou-Embedding-Zh'

In [1]:
import os
from huggingface_hub import snapshot_download

# 1. 设置环境变量，使用国内镜像加速下载（非常重要）
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"

def download_bge_reranker():
    # 模型名称
    model_id = "BAAI/bge-reranker-v2-m3"
    
    # 本地保存路径
    local_dir = "e:/rag-project/models/bge-reranker-v2-m3"
    
    print(f"🚀 开始下载模型: {model_id}")
    print(f"📂 将保存至: {local_dir}")
    
    try:
        snapshot_download(
            repo_id=model_id,
            local_dir=local_dir,
            local_dir_use_symlinks=False, # 直接下载文件，不使用符号链接
            ignore_patterns=["*.msgpack", "*.h5", "*.ot"], # 忽略不需要的权重格式
            resume_download=True # 支持断点续传
        )
        print("\n✅ 模型下载完成！")
    except Exception as e:
        print(f"\n❌ 下载失败: {str(e)}")

if __name__ == "__main__":
    # 确保父目录存在
    os.makedirs("e:/rag-project/models", exist_ok=True)
    download_bge_reranker()

🚀 开始下载模型: BAAI/bge-reranker-v2-m3
📂 将保存至: e:/rag-project/models/bge-reranker-v2-m3


e:\rag-project\.venv\Lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
e:\rag-project\.venv\Lib\site-packages\huggingface_hub\file_download.py:979: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(


Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]

miracl-bge-m3.png:   0%|          | 0.00/52.0k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

BEIR-bge-en-v1.5.png:   0%|          | 0.00/56.4k [00:00<?, ?B/s]

BEIR-e5-mistral.png:   0%|          | 0.00/40.2k [00:00<?, ?B/s]

llama-index.png:   0%|          | 0.00/106k [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

CMTEB-retrieval-bge-zh-v1.5.png:   0%|          | 0.00/51.5k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]


✅ 模型下载完成！


In [2]:
import os
from huggingface_hub import snapshot_download

# 1. 设置环境变量，使用国内镜像加速下载
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"

def download_bge_m3():
    # 模型名称
    model_id = "BAAI/bge-m3"
    
    # 本地保存路径（确保和入库脚本中的路径一致）
    local_dir = "e:/rag-project/models/bge-m3"
    
    print(f"🚀 准备下载 BGE-M3 嵌入模型...")
    print(f"📂 目标路径: {local_dir}")
    
    try:
        # 下载模型
        snapshot_download(
            repo_id=model_id,
            local_dir=local_dir,
            local_dir_use_symlinks=False,  # 直接下载文件到目标文件夹
            ignore_patterns=["*.msgpack", "*.h5", "*.ot"], # 忽略非 PyTorch 格式
            resume_download=True  # 支持断点续传
        )
        print("\n✅ BGE-M3 下载成功！你现在可以运行 build_bge_db.py 进行入库了。")
    except Exception as e:
        print(f"\n❌ 下载过程中出现错误: {str(e)}")

if __name__ == "__main__":
    # 确保保存目录存在
    os.makedirs("e:/rag-project/models", exist_ok=True)
    download_bge_m3()

🚀 准备下载 BGE-M3 嵌入模型...
📂 目标路径: e:/rag-project/models/bge-m3


Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

.gitattributes: 0.00B [00:00, ?B/s]

bm25.jpg:   0%|          | 0.00/132k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


miracl.jpg:   0%|          | 0.00/576k [00:00<?, ?B/s]

.DS_Store:   0%|          | 0.00/6.15k [00:00<?, ?B/s]

nqa.jpg:   0%|          | 0.00/158k [00:00<?, ?B/s]

mkqa.jpg:   0%|          | 0.00/608k [00:00<?, ?B/s]

long.jpg:   0%|          | 0.00/485k [00:00<?, ?B/s]

others.webp:   0%|          | 0.00/21.0k [00:00<?, ?B/s]

colbert_linear.pt:   0%|          | 0.00/2.10M [00:00<?, ?B/s]

long.jpg:   0%|          | 0.00/127k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


Constant_7_attr__value:   0%|          | 0.00/65.6k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

model.onnx:   0%|          | 0.00/725k [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

model.onnx_data:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

sparse_linear.pt:   0%|          | 0.00/3.52k [00:00<?, ?B/s]


✅ BGE-M3 下载成功！你现在可以运行 build_bge_db.py 进行入库了。
